baseURL = ""
theme = "introduction"
DefaultContentLanguage = "en"
themesDir = "themes"
publishDir = "public"
title = "Amazon Trackers Bot"

[params]
themeStyle = "auto"
email                        = "zbspace@gmail.com"  
favicon                      = "/img/logo.ico"  
showRSSButton = false
fadeIn = true
fadeInIndex = false
dateFormat = "Jan 2, 2006"


  [params.home]
  introHeight = "fullheight"
 
  localTime = true
  timeZone = "America/Los_Angeles"
  timeFormat = "en-US"



  [[params.social]]
        url   = "https://t.me/AmazonTrackersBot"
        icon  = "telegram" # icon name without the 'fa-'
        icon_pack = "fab"



 [[menu.main]]
     name    = "Contact"
     url     = "#contact"
     weight  = 4
 [[menu.main]]
     name    = "What can you do"
     url     = "#what"
     weight  = 2
 [[menu.main]]
     name    = "How to use it"
     url     = "#how"
     weight  = 3

[[menu.main]]
     name    = "Home"
     url     = "/"
     weight  = 1



[markup]
defaultMarkdownHandler = "goldmark"



[languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"

title = "Introduction"


